// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/game_agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameAgentService_ClientStream_FullMethodName = "/gameagent.GameAgentService/ClientStream"
)

// GameAgentServiceClient is the client API for GameAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameAgentService 游戏代理服务
type GameAgentServiceClient interface {
	// ClientStream 客户端双向流连接
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type gameAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameAgentServiceClient(cc grpc.ClientConnInterface) GameAgentServiceClient {
	return &gameAgentServiceClient{cc}
}

func (c *gameAgentServiceClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameAgentService_ServiceDesc.Streams[0], GameAgentService_ClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameAgentService_ClientStreamClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// GameAgentServiceServer is the server API for GameAgentService service.
// All implementations must embed UnimplementedGameAgentServiceServer
// for forward compatibility.
//
// GameAgentService 游戏代理服务
type GameAgentServiceServer interface {
	// ClientStream 客户端双向流连接
	ClientStream(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedGameAgentServiceServer()
}

// UnimplementedGameAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameAgentServiceServer struct{}

func (UnimplementedGameAgentServiceServer) ClientStream(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedGameAgentServiceServer) mustEmbedUnimplementedGameAgentServiceServer() {}
func (UnimplementedGameAgentServiceServer) testEmbeddedByValue()                          {}

// UnsafeGameAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameAgentServiceServer will
// result in compilation errors.
type UnsafeGameAgentServiceServer interface {
	mustEmbedUnimplementedGameAgentServiceServer()
}

func RegisterGameAgentServiceServer(s grpc.ServiceRegistrar, srv GameAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameAgentService_ServiceDesc, srv)
}

func _GameAgentService_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameAgentServiceServer).ClientStream(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameAgentService_ClientStreamServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// GameAgentService_ServiceDesc is the grpc.ServiceDesc for GameAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gameagent.GameAgentService",
	HandlerType: (*GameAgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStream",
			Handler:       _GameAgentService_ClientStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/game_agent.proto",
}
